# Generated by Django 5.2.6 on 2025-09-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('customer_name', models.CharField(max_length=25)),
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_purchase', models.DateField()),
                ('brand', models.CharField(max_length=20)),
                ('payment_mode', models.CharField(max_length=30)),
            ],
        ),
    ]
